POST http://localhost:8080/api/pilot
Content-Type: application/json

{
  "firstName": "Doug",
  "lastName": "TEST",
  "age": 40
}

###

POST http://localhost:8080/api/aircraft
Content-Type: application/json

{
  "airframe": "tyler's special aircraft",
  "pilot": {
    "id": 1
  }
}


###
POST http://localhost:8080/api/aircraft
Content-Type: application/json

{
  "airframe": "Curt's special aircraft",
  "pilot": {
    "firstName": "Curt",
    "lastName": "Arbtin",
    "age": 30
  }
}

###
GET localhost:8080/api/aircraft

###

GET http://localhost:8080/api/aircraft?pilotId=1

### flight hour ranking view

GET http://localhost:8080/api/pilot/rankings

### aircraft popularity view

GET http://localhost:8080/api/aircraft/popular

### limit to top 2 popular aircraft
GET http://localhost:8080/api/aircraft/popular?limit=2
